### ISSUE TITLE
Merging Łukasz' fork

### ISSUE THREAD

**Issue by brianwarner** [brianwarner/facade#10]
@lukaszgryglicki,

I had a look back to where Facade was when you forked it.  Here are a few hints on what's changed since then.

1) setup.py is much more automated.  It can now create database, users, and tables automatically, and it generates the database connection files automatically.  It can accept user-entered values for the database name, user, and password, or it randomly generates them.

2) You can now use a shared database for affiliation and alias information.  If you have a few instances of Facade, it is a lot easier when you don't have to keep the affiliation and alias info in sync between them.  This also required some new logic in facade-worker.py to detect changes to affiliation and alias data made by other instances, and allowed me to remove it from the web frontend stuff.  But, it also means that when you import gitdm files or make a change directly in the database, you no longer have to nuke your affiliations.

3) Some of the tables have changed.  analysis_data now holds the raw author and committer email, as it was in the patch.  These are in author_raw_email and committer_raw_email.  Also, author_email and committer_email now hold the aliased email.  This is so if you delete an alias mapping, we can roll the author/committer email back to what it was in the patch, rather than holding onto it.

4) Some changes to columns in database tables.  Your best bet is to export your current configs, set up a new instance of facade, and re-import the configs.  This process should work even despite the column changes, as I've tried to keep it from breaking.  However, if it does break, ping me.

5) By default, git repos clone into a subdirectory of facade now, instead of into /opt.  This seemed to make a lot more sense, reduces the risk of collisions and makes it easy to clean up after a short-lived analysis.

I think that's it.

----

One request I have when you are merging, please attempt to organize new files into subdirectories as makes sense.  I'm trying to keep the top level as clean as possible for things related to display, and utilities/ for things related to analysis, as these are two different things.  This also makes setting .htaccess rules a little easier.

Also, before I release I should update the coding style to PEP 008 (spaces instead of tabs, even though it kills me to do so).  However, I will wait to do this until you've done your merge so we don't end up with more manual merging.

**Comment by lukaszgryglicki** [comment]
Most of Your changes will be flawless.
I'm installing it from Dockerfile.
each time I rebuild image it is regenerated from scratch.
I also need totally automatic setup of ALL without ANY user intervention.
This is why I've added some files - most notably `utilities/automatic_setup.py`
It uses command line arguments one by one and assumes they're answers to questions asked by `setup.py`
See how they're used there:
`Dockerfile`
Special: `facade_setup.sh`:
This line
```
python automatic_setup.py c yes facade facade localhost facade no yes admin exampleemail@domain.com admin admin || exit 1
```

I think I'll make it without bigger problems.

**Comment by brianwarner** [comment]
As for the automatic_setup.py, I wonder if a new command line flag for headless input would solve that issue gracefully?  If the current version of setup.py doesn't receive user input during database info, it just creates random strings and uses those for the db's name, db username, and db password.  Perhaps a flag could simply suppress the raw_input prompts?  I think it would work, so long as you have a secure way to pass it the root password and your preferred website credentials.

**Comment by lukaszgryglicki** [comment]
I'll check, but I if won't expose any other port than website port from inside docker container - then this is not a problem at all.

**Comment by lukaszgryglicki** [comment]
Currently I have a problems with doing any ppython-mysqldb call because of utf8mb4.
Investigating.
Seems like Debian jessie used in Dockerfile has too low python-mysqldb verion (1.2.3 while it should have at least 1.2.5).
Merging of files is ready.

**Comment by lukaszgryglicki** [comment]
Status update.
utf8mb4 is OK on jessie when:
Using MySQL server 5.7
Using python-mysqldb 1.2.7

To do so I had to add special server source (to force Jessie not to use default mysql-5.5):
```
# Initial update apt-get
RUN apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5
RUN echo 'deb http://repo.mysql.com/apt/debian jessie mysql-5.7' > /etc/apt/sources.list.d/mysql.list
RUN apt-get update
```
And configure debian backports to make installing newer `python-mysqldb` possible:
```
RUN echo 'deb http://ftp.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/sources.list
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y `cat requirements_stable.txt`
RUN DEBIAN_FRONTEND=noninteractive apt-get -t jessie-backports install -y `cat requirements_backports.txt`
```
And file `requirements_backports.txt` contains only `python-mysqldb` moved out from `requirements_stable.txt`

Now when I have updated my `cncf/gitdm` email mappings, I have few entries with longer Affioliations and VARCHAR(64) is not enough, so I had to change it to `VARCHAR(128)` in `automatic_setup.py` too.

**Comment by lukaszgryglicki** [comment]
Now I have this issue (imported CNCF gitdm settings and attempted to start facade):
```
* Running facade-worker.py
Traceback (most recent call last):
  File "facade-worker.py", line 1355, in <module>
    fill_empty_affiliations()
  File "facade-worker.py", line 906, in fill_empty_affiliations
    cursor.execute(reset_committer, (discover_alias(changed_alias['alias'],changed_alias['alias'])))
TypeError: discover_alias() takes exactly 1 argument (2 given)
Facade complete
```

Will see what's up there

**Comment by lukaszgryglicki** [comment]
Importing CSV files is not working (from old version).
It is not working from new version too (I mean I've added project, exported configuration to csv, removed that project to and them imported back and it was not working.
Apache logs:
```
[Wed Jun 21 09:15:14.411012 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: confirmimport_github in /var/www/html/manage.php on line 486, referer: http://85.222.70.18:8888/configure
[Wed Jun 21 09:15:14.411017 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: import_repos in /var/www/html/manage.php on line 529, referer: http://85.222.70.18:8888/configure
[Wed Jun 21 09:15:14.411022 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: confirmnew_alias in /var/www/html/manage.php on line 551, referer: http://85.222.70.18:8888/configure
[Wed Jun 21 09:15:14.411027 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: new_alias in /var/www/html/manage.php on line 582, referer: http://85.222.70.18:8888/configure
[Wed Jun 21 09:15:14.411032 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: delete_alias in /var/www/html/manage.php on line 601, referer: http://85.222.70.18:8888/configure
[Wed Jun 21 09:15:14.411037 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: confirmnew_affiliation in /var/www/html/manage.php on line 617, referer: http://85.222.70.18:8888/configure
[Wed Jun 21 09:15:14.411042 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: new_affiliation in /var/www/html/manage.php on line 664, referer: http://85.222.70.18:8888/configure
[Wed Jun 21 09:15:14.411051 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: delete_affiliation in /var/www/html/manage.php on line 693, referer: http://85.222.70.18:8888/configure
[Wed Jun 21 09:15:14.411056 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: export_projects_csv in /var/www/html/manage.php on line 708, referer: http://85.222.70.18:8888/configure
[Wed Jun 21 09:15:14.411061 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: import_projects_csv in /var/www/html/manage.php on line 726, referer: http://85.222.70.18:8888/configure
[Wed Jun 21 09:15:14.411066 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: export_repos_csv in /var/www/html/manage.php on line 768, referer: http://85.222.70.18:8888/configure
[Wed Jun 21 09:15:14.419474 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: repo in /var/www/html/repositories.php on line 17, referer: http://85.222.70.18:8888/configure
[Wed Jun 21 09:15:17.818091 2017] [:error] [pid 46] [client 172.17.0.1:50222] PHP Notice:  Undefined index: repo in /var/www/html/repositories.php on line 17, referer: http://85.222.70.18:8888/repositories
```

I don't have time to debug all this stuff, I'll add my repos manually via SQL.

**Comment by lukaszgryglicki** [comment]
Managed to import repositories from SQL dump, but You need to take a look why importing is broken.
My facade is here: http://85.222.70.18:8888
You can even SSH into it: 
```
ssh -o "Port=2222" facade@85.222.70.18
```
Password is facade.
when inside shell, You can become root:
`sudo bash`
Password "facade"
Then go to `/facade` or `/var/www/html` (which is a copy of /facade) and figure out what is happening.

But please let me know when You are going to do something because I need to finish single facade run on all my 69 repos and save DB dump after that.
And it takes hours to finish.

**Comment by brianwarner** [comment]
Thanks for all of this!

- VARCHAR(64) -> VARCHAR(128) is fine with me.  I hadn't hit any email addresses quite that long yet, but there's no harm in doing this.
- Thanks for the catch on line 906, I'll push that fix.
- The undefined indices notice is because I explicitly check for POST variables which may or may not be defined.  This is because I don't want there to be a default action for manage.php - i.e., without the right args it should just exit.  It occurs to me that using ISSET would prevent it from throwing the error.   However, this shouldn't be sufficient to cause the CSV import to fail.  It was working for me before I pushed it, but I will check again today to be sure.  Something sounds not right.
- I'll add the README info as well.

**Comment by lukaszgryglicki** [comment]
Not sure why but facade still process affiliations, it it that slow, or maybe some infinite loop.
I don't want to CTRL+C it because I've waited so long.
I'll leave it running...
:/

**Comment by brianwarner** [comment]
Affiliations are very slow. But they're about 6x faster than the original
way I was doing it :-) I believe this is due to the sheer volume of rows in
the database.

Even if you need to kill it, it would pick up where it left off and you
don't lose anything. It only fills affiliations which are NULL in the
analysis_data table.

**Comment by lukaszgryglicki** [comment]
BTW: I have log level one more than error, where are logs?
Maybe I'll find something there....

**Comment by brianwarner** [comment]
You want the contents of utility_log in the database, although it also echoes anything it's logging to STDERR as well.  If you run at Debug level, it'll tell you which person it's working on.

I hadn't added any sort of log viewer because up until this point I thought I was the only person who needed that, and I always have a database connection open :-) It would be both useful and trivial to add though, and I'll put it on my list.

**Comment by lukaszgryglicki** [comment]
No, I've figured out this already.
Was just doing desc on all tables ...
Hmmm I see one problem:
```
mysql> select * from analysis_data limit 1;
+----------+------------------------------------------+--------------+--------------------+--------------------+-------------+--------------------+----------------+---------------------+--------------------+----------------+-----------------------+-------+---------+------------+--------------------+----------------------------+
| repos_id | commit                                   | author_name  | author_raw_email   | author_email       | author_date | author_affiliation | committer_name | committer_raw_email | committer_email    | committer_date | committer_affiliation | added | removed | whitespace | filename           | date_attempted             |
+----------+------------------------------------------+--------------+--------------------+--------------------+-------------+--------------------+----------------+---------------------+--------------------+----------------+-----------------------+-------+---------+------------+--------------------+----------------------------+
|        1 | 2fd41d83e9ddeb700170afbc77de7d3cb3c99eb0 | Daniel Smith | dbsmith@google.com | dbsmith@google.com | 2016-05-26  | NULL               | Daniel Smith   | dbsmith@google.com  | dbsmith@google.com | 2016-05-27     | NULL                  |    12 |      12 |          4 | mungers/e2e/e2e.go | 2017-06-21 09:46:19.543024 |
+----------+------------------------------------------+--------------+--------------------+--------------------+-------------+--------------------+----------------+---------------------+--------------------+----------------+-----------------------+-------+---------+------------+--------------------+----------------------------+
1 row in set (0.00 sec)

mysql> select count(*) from analysis_data where author_affiliation is not null;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.52 sec)

mysql> select count(*) from analysis_data where author_affiliation is not null;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.50 sec)

mysql> select count(*) from analysis_data where committer_affiliation is not null;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.51 sec)

mysql> 
```

It seems stalled ...
I need to add debug info to see where it halted.

**Comment by brianwarner** [comment]
Hmm, yes, that is odd.

Side note - I can replicate your issue with the config export/import, and I
think I know where the issue is.  I'll get a fix up in a few hours.

On Wed, Jun 21, 2017 at 11:36 AM, Łukasz Gryglicki <notifications@github.com

**Comment by lukaszgryglicki** [comment]
OK, why use db.commit() inside loop?
I think You should commit in bunches - say after all loop.
It should speedup a lot
Eventually before loop:
begin()
on error rollback()
on all succeeded commit()

**Comment by lukaszgryglicki** [comment]
Hmmm crazy..... do You have indices on columns used in queries?
Both:
```
UPDATE analysis_data SET committer_affiliation = NULL WHERE committer_email LIKE CONCAT('%','lukasz@gmail.com')
```
and
```
UPDATE analysis_data SET committer_affiliation = NULL WHERE committer_email = 'lukasz@gmail.com';
```

Takes 1s in mysql.
Did You considered using one transaction for batch processing:
http://www.zyxware.com/articles/2599/how-to-enable-transactions-with-mysql-and-python

Say for entire this loop: `for changed_affiliation in changed_affiliations:`
Before loop do:
```
db.autocommit(False)
c = db.cursor()
```

Use c inside loop but do NOT commit `c.commit()`
Call commit after loop:
```
db.commit()
db.autocommit(True)
```

ANYWAY: problem IS missing index on `committer_email`, `author_email` columns.
Probably indices are missing everywhere!

**Comment by lukaszgryglicki** [comment]
I would add indices on ALL `analysis_data` coulms that are used in any WHERE (are used for searching).
It will speedup 100x imho or more.

**Comment by brianwarner** [comment]
If you think that would help speed things up and would not leave any data
in a partial state, I am totally open to it.  The main reason I did it that
way is that I wanted partial progress to be made should the process be
killed.  This way an error late in the process wouldn't cause everything
before it to be rolled back.  However, if there's a better way to do it I'm
totally open.  I'm not a database expert by any stretch of the
imagination...

On Wed, Jun 21, 2017 at 11:47 AM, Łukasz Gryglicki <notifications@github.com

**Comment by brianwarner** [comment]
Wow, let's try it then!  I'm really grateful for your input, by the way.  I
probably won't get free to test this until tonight, so if you can wait
until then I'll give it a shot.

On Wed, Jun 21, 2017 at 12:01 PM, Łukasz Gryglicki <notifications@github.com

**Comment by lukaszgryglicki** [comment]
Well. Lets leave transactions.... indices are problem see this:
```
mysql> ALTER TABLE analysis_data ADD INDEX (committer_email);
Query OK, 0 rows affected (9.61 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> UPDATE analysis_data SET committer_affiliation = NULL WHERE committer_email LIKE CONCAT('%','lukasz@gmail.com');
Query OK, 0 rows affected (1.13 sec)
Rows matched: 0  Changed: 0  Warnings: 0

mysql> UPDATE analysis_data SET committer_affiliation = NULL WHERE committer_email = 'lukasz@gmail.com';
Query OK, 0 rows affected (0.00 sec)
Rows matched: 0  Changed: 0  Warnings: 0

mysql> UPDATE analysis_data SET committer_affiliation = NULL WHERE committer_email like 'lukasz@gmail.com';
Query OK, 0 rows affected (0.03 sec)
Rows matched: 0  Changed: 0  Warnings: 0

mysql> UPDATE analysis_data SET committer_affiliation = NULL WHERE committer_email like '%lukasz@gmail.com';
Query OK, 0 rows affected (1.24 sec)
Rows matched: 0  Changed: 0  Warnings: 0

```

I've added index. Searching uning index is superfast but using LIKE '%someemail@domain.com' is not.
Why is LIKE used there?

**Comment by lukaszgryglicki** [comment]
I'll give indices a try - but.
Why do You use LIKE.
It will be 1000x slower because LIKE cannot use index (imho) - need to google for that.

**Comment by brianwarner** [comment]
I think that's already fixed upstream.  It should be an exact match.

**Comment by lukaszgryglicki** [comment]
OK so I'll check upstream.

**Comment by brianwarner** [comment]
However, for domain matching I used LIKE because it should also match subdomains.  e.g., ibm.com should also match us.ibm.com

**Comment by lukaszgryglicki** [comment]
OK, I'm talking about developers emails.
Also You should consider adding INDEX on every column in every table that is used for searching.
I don't know Your project that well.
My suggestion is to:
Search for all queries conditions in all PY and PHP files (search for where, having etc.).
For all columns used there do:
`ALTER TABLE table_name ADD INDEX (column_name);` in `setup.py` file.

**Comment by lukaszgryglicki** [comment]
Took a look on facade-worker.py.
3 tables will need indices:
analysis_data on: *_email, *_affiliation, *_date, repos_id, commit, *_raw_*
aliases: alias
affiliations: domain

Also I suggest (then it can use indices 100-1000x faster):
```
                set_author_to_null = ("UPDATE analysis_data SET author_affiliation = NULL "
-                       "WHERE author_email LIKE CONCAT('%%',%s)")
+                       "WHERE author_email = %s")
 
                cursor.execute(set_author_to_null, (changed_affiliation['domain'], ))
                db.commit()
 
                set_committer_to_null = ("UPDATE analysis_data SET committer_affiliation = NULL "
-                       "WHERE committer_email LIKE CONCAT('%%',%s)")
+                       "WHERE committer_email = %s")
 
                cursor.execute(set_committer_to_null, (changed_affiliation['domain'], ))
                db.commit()
@@ -881,13 +881,13 @@ def fill_empty_affiliations():
                        changed_alias['alias'])
 
                set_author_to_null = ("UPDATE analysis_data SET author_affiliation = NULL "
-                       "WHERE author_raw_email LIKE CONCAT('%%',%s)")
+                       "WHERE author_raw_email = %s")
 
                cursor.execute(set_author_to_null,(changed_alias['alias'], ))
                db.commit()
 
                set_committer_to_null = ("UPDATE analysis_data SET committer_affiliation = NULL "
-                       "WHERE committer_raw_email LIKE CONCAT('%%',%s)")
+                       "WHERE committer_raw_email = %s")
 
                cursor.execute(set_committer_to_null, (changed_alias['alias'], ))
                db.commit()
```

I'll test this in docker now.
I'll add code to create indices to `setup.py`

**Comment by lukaszgryglicki** [comment]
This is what I've added to `setup.py`
```
        # `analysis_data` table indices:
        cursor.execute("alter table analysis_data add index(repos_id)")
        cursor.execute("alter table analysis_data add index(commit)")
        cursor.execute("alter table analysis_data add index(author_raw_email)")
        cursor.execute("alter table analysis_data add index(author_email)")
        cursor.execute("alter table analysis_data add index(author_date)")
        cursor.execute("alter table analysis_data add index(author_affiliation)")
        cursor.execute("alter table analysis_data add index(committer_raw_email)")
        cursor.execute("alter table analysis_data add index(committer_email)")
        cursor.execute("alter table analysis_data add index(committer_date)")
        cursor.execute("alter table analysis_data add index(committer_affiliation)")
(...)
        # `aliases` table indices: 
        cursor_people.execute("alter table aliases add index(canonical)")
        cursor_people.execute("alter table aliases add index(alias)")
(...)
                # `affiliations` table indices: 
                cursor_people.execute("alter table affiliations add index(domain)")
                cursor_people.execute("alter table affiliations add index(affiliation)")
```

**Comment by lukaszgryglicki** [comment]
Actually aliases and affiliations already have indices because of `UNIQUE` in table creation.
So only analysis_data need to create indices

**Comment by lukaszgryglicki** [comment]
YES FINALLY, I see about 300x speedup on affiliations computing!!

**Comment by brianwarner** [comment]
THAT IS AMAZING.  Well done!  I can't wait to merge this.

**Comment by lukaszgryglicki** [comment]
not yet committted

**Comment by lukaszgryglicki** [comment]
Took `Completed in 0:09:31` instead of infinity?? (I've gave up after about 6 hours today) to compute affiliations. 
On such a big data (an there are 8800+ affliations in email-mapping):
![screen shot 2017-06-21 at 19 49 16](https://user-images.githubusercontent.com/2469783/27398737-f97f774c-56ba-11e7-80f3-f3552fcb1965.png)

You need to take a look on those 2 files:
https://github.com/lukaszgryglicki/facade/blob/master/utilities/automatic_setup.py
https://github.com/lukaszgryglicki/facade/blob/master/utilities/facade-worker.py

**Comment by brianwarner** [comment]
Wow.  That's quite a lot of code.  It takes me ~8 hours for the initial run
on 32M lines of code, so I can believe it was still going.  Of course,
that's only going to be a factor on the initial run because it has to catch
up on years worth of data, and afterwards it's only incremental.  But
still, that much performance gain is _so_ worth it.

**Comment by lukaszgryglicki** [comment]
Now when I run `python facade-worker.py -r` (last stage manually) I see:
```
* Option set: rebuilding caches.
* Running facade-worker.py
* Caching unknown affiliations and web data for display
* Deleting old cached unknown affiliations and web data
* Deleting old cached unknown affiliations and web data (complete)
Traceback (most recent call last):
  File "facade-worker.py", line 1358, in <module>
    rebuild_unknown_affiliation_and_web_caches()
  File "facade-worker.py", line 1140, in rebuild_unknown_affiliation_and_web_caches
    cursor.execute(cache_projects_by_month)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
_mysql_exceptions.InternalError: (3, "Error writing file '/tmp/MYpaFxqR' (Errcode: 28 - No space left on device)")
```
I give up for today.

**Comment by lukaszgryglicki** [comment]
Give my indices a shot - You will be scared how faster it is :P

**Comment by brianwarner** [comment]
I found out why import is broken, and it has to do with a very simple
sanity check which verifies that the file being imported is correctly
formatted.  The fix is easy (the files were being exported without utf-8
BOMs).  I'm pushing it now.

Also, I pushed the patch that gets rid of those extraneous warnings from
manage.php.

Any config files you export should work now.  But if you need one you
exported before 926357124cc07f84247b02e65603e59aabd4f781, you can fool the
sanity check by editing the CSV file and inserting a single space on row 1,
before the first column header in the CSV file.  It's an embarrassing
one-time fix, but it'll at least ensure you don't have to enter your
project and repo definitions again.

**Comment by brianwarner** [comment]
I still can't believe the times you were seeing.  Your dataset is 4x larger
than mine, and orders of magnitude faster!

So since you're running out of drive space, one suggestion is to move your
start date forward a few years.  That data will be trimmed out of the
database and you'll get a few bytes back :-)

**Comment by lukaszgryglicki** [comment]
This is NOT dataspace problem. Never.
I wonder why error message is like this.
As for CSV imports.... I'll merge Your fixes.
I've just got my project + repos config from my prefious mysqldump so no problem.
Imported manually via `mysql < blablabla.sql`

**Comment by lukaszgryglicki** [comment]
Gotta go, see You tomorrow.
I'm working 13,5 hours already and I'm dead wasted.

**Comment by lukaszgryglicki** [comment]
Believe in this.  This is just Database indices in play.  This is why thye were created!! Dnia 21 czerwca 2017 20:13 Brian Warner &lt;notifications@github.com&gt; napisał(a):  I still can&#39;t believe the times you were seeing.  Your dataset is 4x larger   than mine, and orders of magnitude faster!      So since you&#39;re running out of drive space, one suggestion is to move your   start date forward a few years.  That data will be trimmed out of the   database and you&#39;ll get a few bytes back :-)      On Wed, Jun 21, 2017 at 1:58 PM, Łukasz Gryglicki &lt;notifications@github.com&gt;   wrote:      &gt; Give my indices a shot - You will be scared how faster it is :P   &gt;   &gt; —   &gt; You are receiving this because you authored the thread.   &gt; Reply to this email directly, view it on GitHub   &gt; &lt;https://github.com/brianwarne   &gt; or mute the thread   &gt; &lt;https://github.com/notificati   &gt; .   &gt;     —  You are receiving this because you were mentioned.  Reply to this email directly,  github.com view it on GitHub , or  github.com mute the thread .

**Comment by brianwarner** [comment]
Thank you for all your contributions today.  I can't tell you how much I
appreciate them!

**Comment by lukaszgryglicki** [comment]
Would be also nice if You add percent statictics to Facade some day, something like gitdm outputs.
We're using custom gitdm for CNCF (kubenrtes repos), like here:
https://github.com/cncf/gitdm
Specially report like this one:
https://github.com/cncf/gitdm/blob/master/all.txt

**Comment by brianwarner** [comment]
That would be quite easy, as the data is all there in the database. Can you
add it as an issue, please? That may be the easiest way to track feature
requests.

**Comment by lukaszgryglicki** [comment]
Now rerun facade (full run) on all data 157M lines of code:
```
Completed in 2:34:57
Facade complete
```
![Uploading Screen Shot 2017-06-22 at 03.15.21.png…]()
![screen shot 2017-06-22 at 03 15 43](https://user-images.githubusercontent.com/2469783/27413051-4dc33bc0-56f9-11e7-8a81-34b38e712cc0.png)
![screen shot 2017-06-22 at 03 16 00](https://user-images.githubusercontent.com/2469783/27413054-4dc82f04-56f9-11e7-8de7-7abbc8489397.png)
![screen shot 2017-06-22 at 03 16 43](https://user-images.githubusercontent.com/2469783/27413052-4dc37068-56f9-11e7-8340-c7dc584a833a.png)
![screen shot 2017-06-22 at 03 16 55](https://user-images.githubusercontent.com/2469783/27413053-4dc58c68-56f9-11e7-87c1-0563d4ff2004.png)

**Comment by brianwarner** [comment]
That's great!  I'm working on the indices now.  I did a bit of reading, and will share what I learned and how I'm using it to sanity check.

Single column indexing seems pretty straight-forward, but multi-column gets a little more interesting.  The order of the columns in each Index statement affects whether a given INDEX will be used.  In particular, if you use a multi-column index (e.g., INDEX (col1,col2,col3)), the index will be used for queries that include all three columns in the WHERE clause, or which are a subset of the columns starting from the left.  So this will cover (col1), (col1,col2), and (col1,col2,col3).  It does not include (col2), (col2, col3), or (col1,col3).

As such, I'm going through and making sure the order of the columns in the existing UNIQUE index columns match what is in the queries.  I've found a few cases where I'll have to reorder them.  I'm also going through each SELECT statement to add appropriate multi-column INDEXes.  I am trying to minimize the number of new columns if at all possible.

After I do this in facade-worker.py, I'll move on to the web code.  I'm putting these in the setup.py CREATE statements, but will send you a list of ALTER statements for your existing tables that will match what I'm putting in setup.py (if you don't want to rebuild the data)

**Comment by brianwarner** [comment]
I definitely see an improvement on a small data set. As expected it didn't
affect analysis, but filling null affiliations was definitely faster. I'm
running it on a larger dataset overnight just to be sure.

**Comment by lukaszgryglicki** [comment]
Also creating final cache was quite slow - it uses 4 or 5 complex report like queries.
But for me it is fast enough now (2,5 hours for all of my data for all time).

**Comment by brianwarner** [comment]
Wow, I see an 8x acceleration on a database with 1.2M rows when filling
affiliations!

Analysis and caching will both be slow, but for separate reasons.  Analysis
won't be helped by indexing because it's a matter of scraping the patches
and inserting the data.  Caching uses JOIN statements, which (as far as I
can tell) aren't helped by INDEXes.  But still, this is great!  Discovering
affiliations went from 2 hours down to 14 minutes.

I also went through the PHP files, and found some additional INDEXes that
should make the website move a little faster.

I'm pushing the new setup.py now.  In the meantime, here's what I'm using
if you want to alter your tables.

ALTER TABLE affiliations ADD INDEX (domain,active);
ALTER TABLE aliases ADD INDEX (alias,active);
ALTER TABLE analysis_data ADD INDEX (author_email,author_
affiliation,author_date);
ALTER TABLE analysis_data ADD INDEX (committer_email,committer_
affiliation,committer_date);
ALTER TABLE analysis_data ADD INDEX (repos_id,commit);
ALTER TABLE analysis_data ADD INDEX (author_raw_email);
ALTER TABLE analysis_data ADD INDEX (committer_raw_email);
ALTER TABLE analysis_data ADD INDEX (author_affiliation);
ALTER TABLE analysis_data ADD INDEX (committer_affiliation);

ALTER TABLE repos_fetch_log ADD INDEX(repos_id,status);
ALTER TABLE analysis_log ADD INDEX (repos_id);

ALTER TABLE project_monthly_cache ADD INDEX (projects_id,year,email);
ALTER TABLE repo_monthly_cache ADD INDEX (repos_id,year,email);

ALTER TABLE project_monthly_cache ADD INDEX (projects_id,year,affiliation);
ALTER TABLE repo_monthly_cache ADD INDEX (repos_id,year,affiliation);

ALTER TABLE project_annual_cache ADD INDEX (projects_id,affiliation);
ALTER TABLE project_monthly_cache ADD INDEX (projects_id,affiliation);
ALTER TABLE repo_annual_cache ADD INDEX (repos_id,affiliation);
ALTER TABLE repo_monthly_cache ADD INDEX (repos_id,affiliation);

ALTER TABLE project_annual_cache ADD INDEX (projects_id,email);
ALTER TABLE project_monthly_cache ADD INDEX (projects_id,email);
ALTER TABLE repo_annual_cache ADD INDEX (repos_id,email);
ALTER TABLE repo_monthly_cache ADD INDEX (repos_id,email);

**Comment by lukaszgryglicki** [comment]
I would give a name to all indices.
like alter table `tbname` add index `iname`(`col1`, `col2`, ...);

**Comment by brianwarner** [comment]
Is the name required or does it help in some way?  I wasn't really clear on
that.

On Thu, Jun 22, 2017 at 12:16 PM, Łukasz Gryglicki <notifications@github.com

**Comment by lukaszgryglicki** [comment]
It is useful when You go to `mysql>` and ask:
`show index from table_name`;

**Comment by brianwarner** [comment]
Good point!  I'll add names and re-push.

On Thu, Jun 22, 2017 at 12:22 PM, Łukasz Gryglicki <notifications@github.com

**Comment by brianwarner** [comment]
Cleaning up this open but dormant ticket.
