### ISSUE TITLE
Feature: author email equivalence table for grouping commits from multiple addresses

### ISSUE THREAD

**Issue by chrisinmtown** [brianwarner/facade#27]
I would like to request a feature that would allow a Facade administrator to list equivalent email addresses for a person's primary email address.  Here are use cases:
1. Our git repo has some errors in it, where people mis-configured their git client and added commits with invalid email addresses.  I would like to associate any invalid address(es) with the valid address, so the domain report doesn't show "unknown affiliation."
2. Our git repo has commits from people who used both an external and internal email address in their commits.  Again I would like to list the equivalences so "joe@company.com" and "joe.open.source@gmail.com" are grouped together for purposes of showing statistics.

Thanks in advance for considering it.

**Comment by brianwarner** [comment]
Hi @chrisinmtown,

I believe this can be accomplished by using aliases.  When you add an alias, either from the list of unknown emails or on the aliases page, it performs this linkage.  This will then be reflected in the analysis data the next time you run facade-worker.py.

Of course, sometimes mistakes are made.  Facade keeps track of the original email address associated with the commit, so if you delete the alias the original email address is restored.

**Comment by chrisinmtown** [comment]
Hi @brianwarner thanks, I think you're telling me this feature is already implemented. I'll go ask for help with configuring this.

**Comment by brianwarner** [comment]
Yep, that's right :-)

When you have an unknown email and are logged in, you should be able to see a button called "Add an alias".  That's probably the most straightforward way to do it.

If that does end up being what you're looking for, please go ahead and close the ticket.  If it isn't, please let me know.

**Comment by chrisinmtown** [comment]
I'll take your word for it, closing.
