### ISSUE TITLE
Feature: report comment statistics by author as reviewer

### ISSUE THREAD

**Issue by chrisinmtown** [brianwarner/facade#28]
Please extend Facade to include descriptive statistics about the comments posted by a person in Gerrit.  Some people are very active as reviewers but less so as committers, and the stats today focus on commits. Comments are valuable, and showing stats about comments would highlight the value of reviewers in an open-source community.

**Comment by chrisinmtown** [comment]
I just read the README and learned that Facade works by cloning a git repo and reporting on what it finds in the commits.  I had mistakenly thought that Facade might read the Gerrit data interface.  So this means Gerrit comments & reviews are not within reach.  So I will close this again, sorry to take your time.

**Comment by brianwarner** [comment]
No need to apologize for questions :-)

Before we get away from this, does Gerrit provide an API for comment and review info?  If so, it may be worth considering.  Github does, and in the long term it may be useful to display metadata like this.  It would be useful to know.
