### ISSUE TITLE
Relicense to MIT

### ISSUE THREAD

**Issue by brianwarner** [brianwarner/facade#32]
@lukaszgryglicki and @mkdolan,

I've had a request from @sgoggins to relicense Facade as MIT so it can be more easily packaged into Augur.  You've both made commits.  Are you both ok with this?

**Comment by mkdolan** [comment]
+1 yes I am

**Comment by lukaszgryglicki** [comment]
+1

**Comment by brianwarner** [comment]
Thank you!  I'll relicense on the next release.

cc/ @sgoggins
